db.js

We want to store lists of e.g. links as a JSON object in SQLite. Currently the code stores them as a comma-separated list, which makes it harder to query. This changes the logic to store JS objects as JSON (unless they are Dates, in which case we store the ISO string).

Properly store lists as JSON

---

db.js
index.js

Since we're only crawling a single host, and we've told the crawler not to crawl URLs on other hosts, there's no point in keeping a `host` column in the database. Let's remove it to save a little space.

Don't bother to store page host

---

db.js
index.js
package.json
parser.js
yarn.lock

This change adds a second SQLite table, `cfgov_fts`, which can be searched using SQLite FTS5 full-text search extension:
https://www.sqlite.org/fts5.html
This is created as an "external content table", which means that the main table content is not duplicated into the FTS table, but only referenced. This should significantly reduce the storage requirements of creating the FTS table.
A SQLite INSERT trigger is created to ensure that when content is added to the main table by the crawl, a reference to it gets added to the FTS table. I haven't created DELETE or UPDATE triggers as we shouldn't/won't be updating table content once it is written, but that is something we could do in future if need be:
https://www.sqlite.org/fts5.html#external_content_tables
This change also adopts the use of …

Create full-text search table

---

parser.js

Store page links and components in a sorted order, instead of the order they appear on the page.

Sort page links and components

---

db.js

This commit adds a new database index for the `cfgov.timestamp` column. This significantly speeds up any DB queries that use this column, for example to find the minimum and maximum timestamps so as to determine when a particular crawl database was generated.

Add database index for crawl timestamp

---

README.md

Document examples of how to use the SQLite command-line client.

Add documentation on common SQLite queries

---

viewer/settings.py

Currently the django-debug-toolbar sidebar is expanded by default. Let's collapse it by default instead.

Collapse django-debug-toolbar by default

---

viewer/viewer/static_src/crawsqueal.js
viewer/viewer/templates/viewer/base_search.html
viewer/viewer/templates/viewer/search_form.html
viewer/viewer/templates/viewer/search_side_bar.html

Currently there are two forms so if you change a sidebar option and also
the search term, you'd have to click both submit buttons. Some JS has been
added that syncs the sidebar values to the search form immediately before
submitting the search form.
Fixes https://github.com/cfpb/crawsqueal/issues/14

Improve UX by combining filter form and search form

---

viewer/settings.py
viewer/viewer/database.py
viewer/viewer/templates/viewer/base.html
viewer/viewer/templates/viewer/base_search.html
viewer/viewer/templates/viewer/page_detail.html
viewer/viewer/templates/viewer/page_list.html
viewer/viewer/templates/viewer/search_form.html
viewer/viewer/templatetags/viewer.py
viewer/viewer/urls.py
viewer/viewer/views.py

This commit adds a link to the page footer to download the SQLite database file. The link includes the size of the file to be downloaded, plus a link to instructions to query it in SQLite.
If there is no database file available to the app, the link is hidden.
Closes #11.
|Footer with database link|Footer without database link|
|-|-|
|<img width="1440" alt="image" src="https://user-images.githubusercontent.com/654645/172939589-ad9ffac0-0556-481c-9e7d-0e0f81232094.png">|<img width="1440" alt="image" src="https://user-images.githubusercontent.com/654645/172939682-cbb15098-e776-4c94-9e36-112771186f07.png">|

Add database download link to page footer

---

viewer/viewer/templates/viewer/page_list.html

This commit hides the CSV download link if there are no results to show.
Closes #23.

Hide CSV download link if there are no results

---

viewer/requirements.txt
viewer/settings.py
viewer/viewer/context_processors.py
viewer/viewer/forms.py
viewer/viewer/pagination.py
viewer/viewer/renderers.py
viewer/viewer/serializers.py
viewer/viewer/templates/viewer/component_list.html
viewer/viewer/templates/viewer/page_detail.html
viewer/viewer/templates/viewer/page_list.html
viewer/viewer/templates/viewer/search_form.html
viewer/viewer/templates/viewer/search_side_bar.html
viewer/viewer/templatetags/page_display.py
viewer/viewer/urls.py
viewer/viewer/views.py
viewer/warc/models.py
viewer/warc/search.py

This PR makes significant changes to the way the viewer gets its data and renders its views:
- All data models now live in the `warc` app and are assumed to have been loaded from a WARC archive via `manage.py warc_to_db`. The former Node-based crawler approach is now deprecated; that code needs to be removed from this repository.
- Almost all views are now rendered by django-rest-framework, which allows for debugging of data via JSON, CSV, and interactive DRF API views.
Testing:
- Run a local server with a WARC-based database: `CRAWL_DATABASE=./crawl.sqlite3 viewer/manage.py runserver`
- Homepage reflects the full dataset: http://localhost:8000/
- clicking "Download CSV file" downloads a large CSV with one row per URL, including language: http://localhost:8000/?format=csv
- manually …

Migrate to new data models and DRF-based views

---

viewer/viewer/templates/viewer/base.html
viewer/viewer/templates/viewer/base_search.html
viewer/viewer/templates/viewer/component_list.html
viewer/viewer/templates/viewer/help.html
viewer/viewer/urls.py

This commit adds a stub help / common searches page, accessible atthe /help/ URL locally.
Content and design is loosely copied from internal designs. Seeinternal el-camino#636 for reference and discussion.

Prototype help / common searches page

---

viewer/warc/search.py
wget_crawl.sh

This PR enhances how link search works so that it includes results that link to a urlencoded version of the provided query string. For example, searching for `https://www.ftc.gov` will now match pages that both have links with `https://www.ftc.gov` but also pages with `https%3A%2F%2Fwww.ftc.gov`.
This is intended to support "external links" on consumerfinance.gov, e.g. links like [this one](https://www.consumerfinance.gov/external-site/?ext_url=https%3A%2F%2Fwww.facebook.com%2FCFPB&signature=mLDxq_fH8p2jVLrkPngPqkmwdsl_JEMSCoqZ74gLcCY) that point to an interstitial page but include an encoded version of the target URL in their query string parameters.
This PR also modifies the wget crawler script to skip these external link pages when crawling cf.gov; specifically those pages that have …

Better link search for external links

---

.github/workflows/test.yml
README.md

The current GitHub Action for Python linting using black wasn't actually doing anything. This PR fixes that, and adds documentation about black to the project README.

Fix and document Python linting with black

---

viewer/requirements.txt

Django version 4.0.3 has several high severity security bugs fixed in more recent versions:
https://docs.djangoproject.com/en/4.0/releases/4.0.4/
https://docs.djangoproject.com/en/4.0/releases/4.0.6/
These patch version upgrades shouldn't affect any functionality in this project.
To test, with the project virtualenv activated, re-run
```
pip install -r viewer/requirements.txt
```
and confirm that all functionality continues to work.

Bump Django version from 4.0.3 to 4.0.6

---

viewer/viewer/templates/viewer/page_list.html

1. The pagination links were inadvertently broken in 6f69fc733fae2d90de65fa67c47a7a8b8ed28153; to test this you need a local DB with more than one page of results. Bug is also visible on the production site currently.
2. The page detail links currently have an extra bit of underline, unfortunately due to how Prettier tries to rearrange tags (see commit message for greater detail).
|Before|After|
|-|-|
|<img width="438" alt="image" src="https://user-images.githubusercontent.com/654645/182168321-07d13214-7ac1-4567-8e45-302cb161673d.png">|<img width="428" alt="image" src="https://user-images.githubusercontent.com/654645/182168382-a60d7808-4f04-4658-b8da-01ab60f7f027.png">|

Minor frontend link fixes

---

viewer/viewer/templates/viewer/base.html

This change modifies the base page template to add footer links to:
- Download website errors (including 404s) as CSV
- Download website redirects as CSV
- Explore website data via API: pages, components, errors, redirects
With this change, the footer now looks like this:

Add additional footer links

---

viewer/viewer/templates/viewer/component_list.html

To test, run with a database that has some design components:
http://localhost:8000/components/
(Or confirm that the page is currently broken in production, and that this will fix it.)

Fix link from components page

---

viewer/viewer/static_src/crawsqueal.css
viewer/viewer/templates/viewer/help.html
viewer/viewer/templates/viewer/search_form.html

Adjusted Help page layout based on Jenn's feedback and now have proper links under the `Component` radio button in the search panel.

Adjust layout and implement component section links

---

viewer/viewer/context_processors.py
viewer/viewer/views.py

Give CSV downloads better filenames that indicate the type of the data and the date of the crawl it is associated with, e.g.
pages-20220801.csv
components-20220801.csv
errors-20220801.csv
redirects-20220801.csv

Give CSV downloads better filenames

---

viewer/viewer/serializers.py
viewer/viewer/views.py

This commit improves the column headings and order used in CSV exports:
Pages: url, title, language
Links: url, title, language, link_url
Components: url, title, language, class_name
Errors: url, status_code, referrer
Redirects: url, status_code, referrer, redirect_url

Improve CSV export column headings and order

---

settings.py

Database timestamps are in UTC, but we want them to display on the frontend in US Eastern timezone (technically "America/New_York"). This change makes that happen.
|Before|After|
|-|-|
|<img width="200" alt="image" src="https://user-images.githubusercontent.com/654645/184003755-d8c33ae4-c2e7-4bd6-8f07-ef5700e9518b.png">|<img width="211" alt="image" src="https://user-images.githubusercontent.com/654645/184003810-3aeea20b-ad88-45fa-9af6-97a6069c6365.png">|

Set default timezone to America/New_York

---

viewer/templatetags/search_results.py
viewer/tests/test_templatetags.py

1. Add comma to numbers in summary results: Results should be "1,000 pages", not "1000 pages".
2. Update results strings for null search: "Showing all 1,000 indexed pages" OR "There are no indexed pages" if for some weird reason the database happens to be empty. See internal el-camino#641#issuecomment-318563 for context.

Minor updates to search results text

---

crawler/management/commands/warc_to_db.py
crawler/reader.py

Currently the crawl result can generate pages that live off of the www.consumerfinance.gov domain, due to a quirk in the way that wget works and generates its output:
Specifically, even though we tell wget to only crawl URLs on www.consumerfinance.gov, if we have redirects that point off the site, it will crawl those pages. For example:
www.cf.gov/something -> somewhereelse.com/something
This change makes it so these pages are discarded when we convert from the wget WARC output to the SQLite database.
This behavior can be controlled by a new `--multiple-domains` / `--no-multiple-domains` flag to the warc_to_db management command.

Limit pages to single domain by default

---

viewer/templates/viewer/base_search.html
viewer/templates/viewer/page_list.html
viewer/templatetags/viewer.py
viewer/tests/test_templatetags.py

Timestamp format: "Aug. 11, 2022, 12:54 p.m. EDT"
This new format appears in the header and footer on the search page.

Add timezone to displayed timestamps

---

viewer/templatetags/viewer.py
viewer/tests/test_templatetags.py

Currently times display incorrectly, for example 8:00 PM displays as 20:00 PM. This bug corrects the time formatting to use 12-hour format without a leading zero for the hour, e.g. 8:00 AM or 8:00 PM.

Bug fix: Times should display in 12-hour format

---

fabfile.py

Currently the deployment fabfile has a hardcoded reference to Python 3.8, but there's no reason to hardcode this. We might want to run on Python 3.10, or whatever version of Python is installed on the server.

Remove hardcoded Python version in fabfile

---

README.md
fabfile.py

This commit adds a new Fabric command, `fab configure`, which can be used to configure a RHEL7 server to run the crawler application. This command does the following:
1. Install Node
2. Install Yarn
3. Build a modern version of SQLite
4. Install Python 3
This commit also enhances the existing `fab deploy` command to add Gunicorn logging, plus logrotate to compress and rotate the log files daily. We will keep the last 90 days of logs.
The documentation is also updated to note these things.

Server configuration and deployment improvements

---

fabfile.py

When using the fabfile configuration/deploy scripts, currently SELinux will block logrotate from rotating the log files because /var/log/crawsqueal is owned by the ec2-user account.
This change adds the necessary SELinux configuration so that logrotate should work properly (via the var_log_t permission).

Fix: Give logrotate permission to rotate logs

---

fabfile.py

This commit bumps the Gunicorn timeout to 10 minutes, to avoid timeouts when downloading large files, like the raw SQLite database.

Bump Gunicorn timeout

---

viewer/templates/viewer/base.html

SVG favicons are currently supported by most major browsers except for Safari: https://caniuse.com/link-icon-svg

Set favicon to 🪱

---

crawler/reader.py

Currently if for some reason a page that is otherwise valid (returned an HTTP 200 response and is of type text/html) is missing a <title> tag, the warc_to_db command will fail because titles are not optional.
It might be possible to add support for optional titles, but this would require some changes to the UI (to know how to display links to the page, for example).
This change skips any pages that show up in the WARC like this.

Fix: Skip pages with missing title tags

---

viewer/context_processors.py
viewer/templates/viewer/base_search.html
viewer/templates/viewer/page_list.html
viewer/views.py

If the crawl database has zero pages, the viewer application will currently return an unhandled 500 error.
This commit fixes the viewer application so that it gracefully handles empty databases. It also hides the "Data last updated" indication if there is no date to display.

Graceful handling of empty databases

---

crawler/management/commands/crawl.py

1. Fix bug with overwriting wpull progress DB.
2. Don't base command exit code on wpull's exit code.
Wpull's application class returns a non-zero exit code if there are any URL failures (for example DNS failure). We don't want our entire management command to return non-zero because of this.

Fix two minor bugs related to wpull usage

---

package.json
viewer/static_src/main.js
yarn.lock

This fixes broken expanding on the details page.
- Pull and `yarn && yarn run build`
- Start the local server and visit http://localhost:8000/page/?url=http%3A//localhost%3A8000/
- Note that expanding/collapsing work as expected, contra `<crawler domain>/page/?url=https%3A//www.consumerfinance.gov/about-us/blog/&search_type=html&q=o-expandable_content`

Updates @cfpb/cfpb-expandables to latest (0.32.0)

---

crawler/management/commands/crawl.py
crawler/wpull_plugin.py

Currently the crawl management command always returns a zero exit code even if wpull has some kind of serious error. By default wpull returns a non-zero exit code for *any* failure, which is too sensitive - we don't want downstream processing to fail just because the crawler can't resolve the DNS of a link, for example.
This change reintroduces the wpull exit status codes but only for errors that don't relate to network failures (DNS, connectivity, etc).

Don't base command exit code on wpull's exit code

---

crawler/models.py
crawler/tests/test_models.py
viewer/serializers.py

This change adds two new boolean fields to the redirect data available as a CSV download or via the API:
- is_http_to_https: true if the redirect is only from an http:// URL to the equivalent https:// URL.
- is_append_slash: true if the redirect is only from a URL to the same URL with a trailing slash appended.
To test, visit http://localhost:8000/redirects/?format=api to browse the API or http://localhost:8000/redirects/?format=csv download redirect data as a CSV.

Add two new fields to redirect export

---

fabfile.py
settings.py

This change adds support for running this application on RHEL8.
The fabfile.py configuration and deployment scripts are simplified; RHEL8 includes Python 3.6 so we no longer need to install it, nor a different version of SQLite. We can also use Node 18 instead of Node 16.
The Python application code also needs to be modified to use a more secure version of hashlib.md5 to comply with FIPS mode. See http://blog.serindu.com/2019/11/12/django-in-fips-mode/ for background and the implemented workaround.
I've already tested this manually in our internal cloud environment; see internal CFGOV/crawler-deploy#2 for the associated CloudFormation template changes.

Add support for RHEL8

---

README.md
fabfile.py

This PR updates the repo fabfile.py for deploys to RHEL8. The only change has to do with the location of the crawl database file itself, moving it from /var/tmp to the deploy location in /opt/cfpb/website-indexer. This change is necesssary due to the different volume configuration in our RHEL8 AMI.
These changes have already been deployed manually to our internal crawler deployment, and are running successfully.

Update deploy configuration for RHEL8

---

crawler/wpull_plugin.py

The crawler logic currently skips links to twitter.com; as of https://github.com/cfpb/consumerfinance.gov/commit/846e03a1728bd568e3eefa4ef7ed1e3ccbcaeee1 the CFPB website now links to x.com instead. This change adds x.com to the crawl exclusion list.

Don't crawl URLs on x.com

---

esbuild.mjs
package.json
viewer/static_src/css/skip-nav.less
viewer/static_src/js/main.js
viewer/templates/viewer/base.html
viewer/templates/viewer/component_list.html
viewer/templates/viewer/help.html
viewer/templates/viewer/page_detail.html
viewer/templates/viewer/page_list.html
viewer/templates/viewer/search_form.html
viewer/templates/viewer/search_results.html
yarn.lock

This PR includes some fixups for #96, mainly a fix for broken pagination introduced in that PR. It also bumps Prettier to its latest version 3.3.3 and adds [prettier-plugin-jinja-template](https://github.com/davidodenwald/prettier-plugin-jinja-template) to more sensibly handle Jinja templates without having to use `` throughout.

Pagination fixup; Better Prettier handling of Jinja templates

---

viewer/templates/viewer/page_list.html

Instead of truncating longer page titles, wrap them onto as many lines as they need.
See https://github.local/Design-Development/Design-and-Content-Team/issues/507

Wrap long page titles

---

crawler/wpull_plugin.py
requirements/base.txt
requirements/gunicorn.txt
requirements/test.txt

This PR bumps the version of Django used from 3.2 to 4.2. It also upgrades all other packages to their latest compatible versions. Some packages aren't yet compatible with Django 5.0.

Upgrade Django to 4.2, plus other packages

---

README.md
fabfile.py
requirements/base.txt
settings.py
viewer/context_processors.py
viewer/templates/viewer/page_list.html
viewer/urls.py
viewer/views.py

This commit generalizes the database configuration used by the Django viewer application. Instead of assuming a SQLite database file, this commit alters the project settings to use [dj-database-url](https://github.com/jazzband/dj-database-url) instead, which supports various database backends.
The `DATABASE_URL` parameter must now specify a dj-database-url configuration string instead of a SQLite file path.
Because the viewer backend now supports any database, the ability to download the raw SQLite database file has been removed from the frontend. Deployments that use SQLite as the database storage can provide alternate ways of exposing that file if needed.
The crawler application still deliberately writes to a SQLite file; a subsequent PR will consolidate this with the viewer database …

Generalize viewer database configuration

---

fabfile.py

Commit ba4b5d0bff798ea588e022cd1b35c3e4712b068d failed to modify the fabfile to properly set the `DATABASE_URL` environment variable instead of the `CRAWL_DATABASE` variable, now that this project has been migrated to dj-database-url.
This commit fixes that.

Fix DATABASE_URL environment variable in fabfile

---

.prettierignore
README.md
settings.py
viewer/templates/viewer/base.html
viewer/templates/viewer/gtm/body.html
viewer/templates/viewer/gtm/head.html
viewer/templatetags/gtm.py
viewer/tests/test_loaders.py

This PR adds Google Tag Manager tags to all crawler pages if the `GOOGLE_TAG_ID` environment variable is defined. The README has been updated to document this.
See internal https://github.local/Design-Development/Design-and-Content-Team/issues/516.

Add support for Google Tag Manager

---

crawler/models.py
crawler/tests/test_models.py

The existing logic to query latest crawl results by default has a bug. Instead of returning the latest crawl results, it returns the earliest. This commit fixes that issue and adds a regression unit test.

Fix: Always query latest crawl results

---

Dockerfile
requirements/base.txt

Add libpq and psycopg2 so Django can talk to PostgreSQL.

Add dependencies for connecting to PostgreSQL

---

.dockerignore
README.md
patch_environ/__init__.py
patch_environ/tests/test_patch_environ.py
pyproject.toml
settings.py

As an alternative to configuration via environment variable, this commit allows for configuration from files instead. This avoids the need to populate a container environment with secret values directly.
The `PATCH_ENVIRON_PATH` environment variable can be pointed to a directory containing files named for the variables to set, containing the desired values for those variables.
The README has been updated to document this feature.

Allow configuration from file-based env variables

---

crawler/search.py
viewer/tests/test_views.py

Use of Django filtering with `__contains` queries [case-insensitively on SQLite](https://docs.djangoproject.com/en/5.1/ref/databases/#substring-matching-and-case-sensitivity), but case-sensitively on PostgreSQL. In order to keep case-insensitive search, this commit modifies the logic to use Django [`__icontains`](https://docs.djangoproject.com/en/5.1/ref/models/querysets/#icontains) instead [1].

Explicitly query case-insensitively

---

crawler/management/commands/manage_crawls.py
crawler/tests/test_commands.py

If a crawl job is interrupted, it won't record a final status of `FAILED` or `FINISHED`, but will be left in `STARTED`. The current invocation of "manage.py manage_crawls clean" won't clean up old `STARTED` crawls. This commit modifies the logic of that command to do so, while still retaining the ability to keep 1 completed `FINISHED` and `FAILED` crawl, respectively. The logic won't delete `STARTED` crawls that are the most recent.
Unit tests have been updated to cover this change.

Better cleanup of incomplete crawls

---

esbuild/scripts.js
viewer/static_src/js/main.js

- The generated CSS is handled via the main JS entrypoint. ESBuild reads `main.js` and when encountering the .scss import, it exports the referenced file as `main.css`. When `Expandable` is imported, it too has associated CSS from the DS. With that import coming first, means that it messes up the order of the generated CSS. Moving the `main.scss` import first fixes that.
- Fix typo in cfpb icons path.

Swap scss import order

---

requirements/base.txt

Addresses several CVEs, see release notes: https://docs.djangoproject.com/en/dev/releases/4.2.17/

Bump Django from 4.2.16 to 4.2.17

---

requirements/base.txt

Addresses several CVEs. See release notes:
- https://docs.djangoproject.com/en/5.1/releases/4.2.18/
- https://docs.djangoproject.com/en/5.1/releases/4.2.19/
- https://docs.djangoproject.com/en/5.1/releases/4.2.20/

Bump Django version from 4.2.17 to 4.2.20

---

crawler/wpull/plugin.py

The crawler currently doesn't properly crawl URLs that have been redirected (for example, / -> /complaint/). This commit tries to fix that.

Fix: Properly crawl redirected URLs

---

requirements/base.txt

Addresses CVE-2025-32873. See release notes:
https://docs.djangoproject.com/en/5.1/releases/4.2.21/

Upgrade Django from 4.2.20 to 4.2.21

---

Dockerfile

Fix reported build checks for key/value pairing
See https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/

Update dockerfile key/value format

---

Dockerfile

Building the Docker image for this project currently generates a warning:
> JSON arguments recommended for ENTRYPOINT/CMD to prevent unintended behavior related to OS signals
This change adjusts the `CMD` statement in the Dockerfile to address this warning.
Fixes #135.

Fix Dockerfile warning about JSON arguments

---

requirements/base.txt

Release notes: https://docs.djangoproject.com/en/5.1/releases/4.2.24/

Update Django from 4.2.23 to 4.2.24

---

requirements/base.txt

Addresses two CVEs. See release notes:
https://docs.djangoproject.com/en/5.2/releases/4.2.25/

Bump Django from 4.2.24 to 4.2.25
